(() => {
  'use strict';
  const data = window.COBBLEVERSE_DATA;
  if (!data) return;
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const normalize = value => String(value ?? '').toLowerCase().replace(/[\s_\-:]/g, '');
  const pokemonById = new Map(data.pokemon.map(p => [p.id, p]));
  const pokemonByEnglish = new Map(data.pokemon.map(p => [String(p.en).toLowerCase(), p]));
  const itemById = new Map(data.items.map(i => [i.id, i]));
  const dialog = $('#detail-dialog');
  const dialogContent = $('#dialog-content');
  const typeNames = {normal:'一般',fire:'火',water:'水',electric:'电',grass:'草',ice:'冰',fighting:'格斗',poison:'毒',ground:'地面',flying:'飞行',psychic:'超能力',bug:'虫',rock:'岩石',ghost:'幽灵',dragon:'龙',dark:'恶',steel:'钢',fairy:'妖精'};
  const bucketNames = {common:'常见',uncommon:'少见',rare:'稀有','ultra-rare':'极稀有'};
  const positionNames = {grounded:'地面',submerged:'水下',surface:'水面',seafloor:'水底',air:'空中'};
  const reqNames = {level:'等级',friendship:'亲密度',time_range:'时间',has_move_type:'掌握招式属性',has_move:'掌握指定招式',held_item:'携带道具',biome:'生态域',weather:'天气',moon_phase:'月相',attack_defence_ratio:'攻击与防御关系',party_member:'队伍成员',world:'维度',structure:'结构',recoil:'累计反伤',use_move:'使用招式',damage_taken:'累计承伤',defeat:'击败目标'};
  const fieldNames = {minLevel:'最低等级',maxLevel:'最高等级',amount:'数值',range:'时段',type:'属性',move:'招式',item:'道具',biome:'生态域',weather:'天气',moonPhase:'月相',ratio:'关系',pokemon:'宝可梦',target:'目标',count:'次数'};
  const conditionNames = {biomes:'生态域',dimensions:'维度',structures:'结构',minY:'最低高度',maxY:'最高高度',minSkyLight:'最低天空光',maxSkyLight:'最高天空光',minLight:'最低亮度',maxLight:'最高亮度',timeRange:'出现时间',weather:'天气',moonPhase:'月相',canSeeSky:'需要露天',isRaining:'需要下雨',isThundering:'需要雷暴',fluid:'流体',neededNearbyBlocks:'附近方块',neededBaseBlocks:'脚下方块'};
  const words = {base:'普通形态',normal:'普通',female:'雌性',male:'雄性',alola:'阿罗拉',alolan:'阿罗拉',galar:'伽勒尔',galarian:'伽勒尔',hisui:'洗翠',hisuian:'洗翠',paldea:'帕底亚',paldean:'帕底亚',mega:'超级进化',megax:'超级进化X',megay:'超级进化Y',gigantamax:'超极巨化',gmax:'超极巨化',origin:'起源形态',altered:'别种形态',therian:'灵兽形态',incarnate:'化身形态',school:'鱼群形态',solo:'单独形态',sunny:'晴天形态',rainy:'雨天形态',snowy:'雪天形态',east:'东海',west:'西海',white:'白色',black:'黑色',red:'红色',blue:'蓝色',green:'绿色',yellow:'黄色',pink:'粉色',orange:'橙色',purple:'紫色',gray:'灰色',brown:'棕色',cyan:'青色',violet:'紫罗兰色',lime:'黄绿色',magenta:'品红色',gold:'金色',dark:'深色',light:'浅色',cap:'帽子',partner:'搭档',original:'初始',world:'世界',unova:'合众',kalos:'卡洛斯',hoenn:'丰缘',sinnoh:'神奥',rockstar:'摇滚明星',popstar:'流行明星',libre:'蒙面摔角手',belle:'贵妇',phd:'博士',harry:'哈利',wise:'智慧',saucy:'俏皮',skelly:'骷髅',day:'白天',night:'夜晚',dawn:'黎明',dusk:'黄昏',rain:'下雨',thunder:'雷暴',clear:'晴朗',full_moon:'满月',new_moon:'新月',jungle:'丛林',forest:'森林',desert:'沙漠',ocean:'海洋',river:'河流',beach:'沙滩',mountain:'山地',plains:'平原',swamp:'沼泽',cave:'洞穴',nether:'下界',end:'末地',overworld:'主世界',cold:'寒冷',warm:'温暖',bias:'地区倾向',sheared:'剪毛',regrown:'再生',netherite:'下界合金',iron:'铁',copper:'铜',platinum:'铂金',nickel:'镍',calico:'三花',apricot:'杏色',heart:'爱心',mask:'面具',tiger:'虎纹',zebra:'斑马纹',bubbles:'气泡纹',patches:'斑块纹',stripes:'条纹',diamonds:'菱形纹',diamond:'钻石',raindrops:'雨滴纹',forehead:'额头纹',orca:'虎鲸纹',dapples:'斑点纹','two-tone':'双色',tree:'树木',star:'星星',glasses:'眼镜',fluff:'绒毛',full:'完整',berry:'树果',clover:'四叶草',flower:'花朵',ribbon:'缎带',strawberry:'草莓',matcha:'抹茶',mint:'薄荷',ruby:'红宝石',lemon:'柠檬',salted:'盐味',caramel:'焦糖',vanilla:'香草',tail:'尾巴',shadow:'暗影',wild:'野生',cherry:'樱花',ice:'冰',warped:'诡异',crimson:'绯红',overdrive:'高调形态',ancient:'古代',poke:'精灵',ball:'球',stage1:'阶段1',stage2:'阶段2',stage3:'阶段3',stage4:'阶段4',stage5:'阶段5',stage6:'阶段6',stage7:'阶段7'};
  const recipeNames = {crafting_shaped:'有序合成',crafting_shapeless:'无序合成',smelting:'熔炉烧炼',blasting:'高炉烧炼',smoking:'烟熏炉加工',campfire_cooking:'营火烹饪',stonecutting:'切石机加工',smithing_transform:'锻造台升级',smithing_trim:'锻造纹饰'};
  const shopNames = {'Cobble Ball':'精灵球','Potions':'药品','Mob Drops':'生物掉落','Cards':'卡片'};

  const sprite = (p, className='pokemon-sprite') => p?.image ? `<img class="${className}" src="${escapeHtml(p.image)}" alt="${escapeHtml(p.name)}头像" loading="lazy">` : `<span class="poke-silhouette">${escapeHtml((p?.name||'?').slice(0,1))}</span>`;
  const itemIcon = (itemId, className='item-icon') => { const item=itemById.get(itemId); return item?.image?`<img class="${className}" src="${escapeHtml(item.image)}" alt="${escapeHtml(item.name)}" loading="lazy">`:`<span class="${className} item-fallback">◇</span>`; };
  function chineseTokens(raw) { const text=String(raw??'').replace(/^#/,'').split(':').pop(); return words[text]||text.split('_').map(x=>words[x]||x).join('·'); }
  function friendly(value) {
    if(value===true)return'是';if(value===false)return'否';if(Array.isArray(value))return value.map(friendly).join('、');
    if(typeof value==='object'&&value)return Object.entries(value).map(([k,v])=>`${fieldNames[k]||chineseTokens(k)}：${friendly(v)}`).join('；');
    const raw=String(value??'');if(itemById.has(raw))return itemById.get(raw).name;const pid=raw.split(/[ :]/)[0].split(':').pop();if(pokemonById.has(pid))return pokemonById.get(pid).name;if(typeNames[raw])return typeNames[raw];return chineseTokens(raw);
  }
  const formLabel = raw => !raw||raw==='base'?'普通形态':raw.split('_').map(x=>words[x]||x).join(' · ');

  $('#stats-strip').innerHTML=[[data.meta.pokemonCount,'宝可梦数据'],[data.meta.spawnCount,'生成条目'],[data.meta.recipeCount,'配方'],[data.meta.itemCount,'道具/方块'],[data.meta.modCount,'启用模组']].map(([v,l])=>`<div class="stat"><strong>${v.toLocaleString()}</strong><span>${l}</span></div>`).join('');
  Object.entries(typeNames).forEach(([id,name])=>$('#type-filter').insertAdjacentHTML('beforeend',`<option value="${id}">${name}</option>`));
  [...new Set(data.pokemon.flatMap(p=>p.labels.filter(x=>/^gen\d+$/.test(x)).map(x=>x.slice(3))))].sort((a,b)=>a-b).forEach(g=>$('#gen-filter').insertAdjacentHTML('beforeend',`<option value="gen${g}">第 ${g} 世代</option>`));
  [...new Set(data.items.map(i=>i.namespace))].sort().forEach(ns=>$('#namespace-filter').insertAdjacentHTML('beforeend',`<option value="${escapeHtml(ns)}">${escapeHtml(ns)}</option>`));

  let pokemonLimit=40;
  function filteredPokemon(){const q=normalize($('#pokemon-search').value),type=$('#type-filter').value,gen=$('#gen-filter').value,mode=$('#spawn-filter').value;return data.pokemon.filter(p=>(!q||[p.name,p.en,p.id,p.dex,...p.spawns.flatMap(s=>(s.biomes||[]).map(b=>b.name))].some(v=>normalize(v).includes(q)))&&(!type||p.typeIds.includes(type))&&(!gen||p.labels.includes(gen))&&(!mode||(mode==='spawn'&&p.spawns.length)||(mode==='evolution'&&data.pokemon.some(x=>x.evolutions.some(e=>e.result===p.id)))||(mode==='special'&&!p.spawns.length)));}
  function renderPokemon(reset=false){if(reset)pokemonLimit=40;const list=filteredPokemon();$('#pokemon-count').textContent=`找到 ${list.length.toLocaleString()} 只宝可梦 · 当前显示 ${Math.min(list.length,pokemonLimit).toLocaleString()} 只`;$('#pokemon-grid').innerHTML=list.slice(0,pokemonLimit).map((p,index)=>`<button class="pokemon-card" style="animation-delay:${Math.min(index,15)*18}ms" type="button" data-pokemon="${p.id}"><span class="pokemon-visual"><span class="dex-number">#${String(p.dex??'—').padStart(4,'0')}</span>${sprite(p)}</span><span class="pokemon-body"><h3>${escapeHtml(p.name)}</h3><span class="types">${p.typeIds.map(t=>`<span class="type ${t}">${typeNames[t]||t}</span>`).join('')}</span><small>全国图鉴 ${p.dex??'—'} · ${p.spawns.length?`${p.spawns.length} 条获取数据`:'特殊获取'}</small></span></button>`).join('');$('#pokemon-more').hidden=pokemonLimit>=list.length;}

  let itemLimit=60;
  function filteredItems(){const q=normalize($('#item-search').value),ns=$('#namespace-filter').value,source=$('#source-filter').value;return data.items.filter(i=>(!q||[i.name,i.id].some(v=>normalize(v).includes(q)))&&(!ns||i.namespace===ns)&&(!source||(source==='known'&&i.hasSource)||(source==='recipe'&&i.recipes.length)||(source==='shop'&&i.shops.length)||(source==='drop'&&i.pokemonDrops.length)||(source==='loot'&&i.loot.length)||(source==='unknown'&&!i.hasSource)));}
  function itemTags(i){const tags=[];if(i.recipes.length)tags.push('合成');if(i.shops.length)tags.push('商店');if(i.pokemonDrops.length)tags.push('宝可梦掉落');if(i.loot.length)tags.push('战利品');return tags.length?tags.map(x=>`<span class="source-tag known">${x}</span>`).join(''):'<span class="source-tag unknown">未检出来源</span>';}
  function renderItems(reset=false){if(reset)itemLimit=60;const list=filteredItems();$('#item-count').textContent=`找到 ${list.length.toLocaleString()} 项 · ${list.filter(i=>i.hasSource).length.toLocaleString()} 项有可追溯来源`;$('#item-list').innerHTML=list.slice(0,itemLimit).map(i=>`<button class="item-card" type="button" data-item="${escapeHtml(i.id)}"><span class="item-card-main">${itemIcon(i.id)}<span><h3>${escapeHtml(i.name)}</h3><small>${i.hasSource?'已收录获取方式':'仅收录物品信息'}</small></span></span><span class="source-dots">${itemTags(i)}</span></button>`).join('');$('#item-more').hidden=itemLimit>=list.length;}

  function formatCondition(obj){const entries=Object.entries(obj||{});return entries.length?entries.map(([k,v])=>`<span class="chip"><b>${conditionNames[k]||chineseTokens(k)}</b>：${escapeHtml(friendly(v))}</span>`).join(''):'<span class="empty">无附加限制</span>';}
  function formatRequirement(req){const details=Object.entries(req).filter(([k])=>k!=='variant').map(([k,v])=>`${fieldNames[k]||chineseTokens(k)}：${friendly(v)}`).join('，');return `${reqNames[req.variant]||chineseTokens(req.variant||'条件')}${details?`（${details}）`:''}`;}
  function edgeText(e){const mode={level_up:'升级时',item_interact:'使用道具',trade:'交换时',passive:'满足条件'}[e.variant]||'满足条件';const reqs=(e.requirements||[]).map(formatRequirement);if(e.context)reqs.unshift(`需要：${friendly(e.context)}`);if(e.form)reqs.unshift(`限定形态：${formLabel(e.form)}`);return`${mode}${reqs.length?' · '+reqs.join('；'):''}`;}
  function spawnEntries(p){return p.spawns.length?p.spawns.map(s=>{const rest={...(s.condition||{})};delete rest.biomes;const biomes=s.biomes||[];return`<div class="data-entry spawn-entry"><div class="spawn-summary"><strong>${bucketNames[s.bucket]||friendly(s.bucket)}</strong><span>等级 ${escapeHtml(s.level||'未指定')}</span><span>${positionNames[s.position]||friendly(s.position)||'位置未指定'}</span><span>刷新权重 ${escapeHtml(s.weight??'—')}</span></div><div class="biome-box"><b>主要刷新生态域</b><div class="biome-list">${biomes.length?biomes.map(x=>`<span>${escapeHtml(x.name)}</span>`).join(''):'<span>未限定特定生态域，或由结构事件控制</span>'}</div></div>${Object.keys(rest).length?`<div class="chip-row">${formatCondition(rest)}</div>`:''}${Object.keys(s.anticondition||{}).length?`<p><b>不会出现于：</b>${escapeHtml(friendly(s.anticondition))}</p>`:''}</div>`}).join(''):'<p class="warning">当前启用的数据中没有常规野外生成记录。它可能来自进化、初始选择、巢穴、结构事件或剧情脚本。</p>';}
  const incoming=id=>data.pokemon.flatMap(p=>p.evolutions.filter(e=>e.result===id).map(e=>({from:p,evo:e})));
  function rootsFor(id,seen=new Set()){if(seen.has(id))return[];seen.add(id);const parents=incoming(id);return parents.length?[...new Set(parents.flatMap(x=>rootsFor(x.from.id,new Set(seen))))]:[id];}
  function chainNode(id,current,trail=new Set()){const p=pokemonById.get(id);if(!p||trail.has(id))return'';const nextTrail=new Set(trail);nextTrail.add(id);const children=p.evolutions.filter(e=>pokemonById.has(e.result));const node=`<button class="chain-node ${id===current?'current':''}" data-pokemon="${id}" type="button">${sprite(p,'')}<span>${escapeHtml(p.name)}</span></button>`;if(!children.length)return node;return`<div class="chain-level">${node}<div class="chain-children">${children.map(e=>`<div class="chain-branch"><span class="chain-arrow"><b>→</b>${escapeHtml(edgeText(e))}</span>${chainNode(e.result,current,nextTrail)}</div>`).join('')}</div></div>`;}
  function evolutionTree(p){const roots=[...new Set(rootsFor(p.id))];return roots.length?`<div class="evolution-tree">${roots.map(r=>chainNode(r,p.id)).join('')}</div>`:'<p class="empty">没有记录到进化关系。</p>';}
  function formsPanel(p){const images=p.images||[];if(!images.length)return'<p class="empty">本地资源包没有可用的形态头像。</p>';const first=images[0];return`<div class="form-preview"><img id="form-preview-image" src="${escapeHtml(first.image)}" alt="${escapeHtml(p.name)}${escapeHtml(formLabel(first.form))}"><div><h3 id="form-preview-title">${escapeHtml(formLabel(first.form))}</h3><p>共读取到 ${images.length} 张普通形态头像。点击下方头像可切换预览。</p></div></div><div class="form-gallery">${images.map((x,n)=>`<button class="form-card ${n===0?'active':''}" type="button" data-form-image="${escapeHtml(x.image)}" data-form-label="${escapeHtml(formLabel(x.form))}"><img src="${escapeHtml(x.image)}" loading="lazy" alt="${escapeHtml(p.name)}${escapeHtml(formLabel(x.form))}"><strong>${escapeHtml(formLabel(x.form))}</strong></button>`).join('')}</div>`;}

  function showPokemon(id,initialTab='obtain'){
    const p=pokemonById.get(id);if(!p)return;const statMap={hp:'体力',attack:'攻击',defence:'防御',special_attack:'特攻',special_defence:'特防',speed:'速度'};
    const drops=p.drops.length?p.drops.map(d=>`<div class="data-entry"><button class="link-button" data-item="${escapeHtml(d.item)}">${escapeHtml(itemById.get(d.item)?.name||friendly(d.item))}</button> · 数量 ${escapeHtml(d.quantity)}${d.chance!=null?` · 概率 ${d.chance}%`:''}</div>`).join(''):'<p class="empty">没有记录到击败掉落。</p>';
    dialogContent.innerHTML=`<article class="detail"><header class="detail-hero">${sprite(p,'detail-portrait')}<div><h2>${escapeHtml(p.name)}</h2><div class="types">${p.typeIds.map(t=>`<span class="type ${t}">${typeNames[t]||t}</span>`).join('')}</div><p>全国图鉴编号 #${p.dex??'—'}</p></div></header><p>${escapeHtml(p.description||'本地语言文件中没有图鉴描述。')}</p><details class="tech-details"><summary>查看英文名与技术标识</summary><code>${escapeHtml(p.en)} · ${escapeHtml(p.id)}</code></details><nav class="detail-tabs" aria-label="图鉴详情切换"><button class="detail-tab" data-tab="obtain">获取方式</button><button class="detail-tab" data-tab="evolution">进化链</button><button class="detail-tab" data-tab="forms">形态图鉴（${p.images?.length||0}）</button><button class="detail-tab" data-tab="stats">能力数据</button><button class="detail-tab" data-tab="drops">掉落物</button></nav><div class="tab-panel" data-panel="obtain"><section class="detail-section"><h3>野外获取条件</h3>${spawnEntries(p)}</section></div><div class="tab-panel" data-panel="evolution"><section class="detail-section"><h3>完整进化链</h3><p>点击链条中的头像可切换到对应宝可梦。</p>${evolutionTree(p)}</section></div><div class="tab-panel" data-panel="forms"><section class="detail-section"><h3>形态外观</h3>${formsPanel(p)}</section></div><div class="tab-panel" data-panel="stats"><section class="detail-section"><div class="fact-grid"><div class="fact"><small>种族值总和</small><strong>${p.bst}</strong></div><div class="fact"><small>捕获率</small><strong>${p.catchRate??'—'}</strong></div><div class="fact"><small>野外记录</small><strong>${p.spawns.length}</strong></div><div class="fact"><small>骑乘类型</small><strong>${escapeHtml(p.ride.map(friendly).join(' / ')||'不可骑乘')}</strong></div></div><h3>基础能力</h3><div class="stat-bars">${Object.entries(p.stats).map(([k,v])=>`<div class="stat-row"><span>${statMap[k]||friendly(k)}</span><b>${v}</b><span class="bar"><i style="width:${Math.min(100,v/2)}%"></i></span></div>`).join('')}</div></section></div><div class="tab-panel" data-panel="drops"><section class="detail-section"><h3>击败掉落</h3>${drops}</section></div></article>`;
    selectTab(initialTab);if(!dialog.open)dialog.showModal();
  }
  function selectTab(name){$$('.detail-tab',dialogContent).forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab-panel',dialogContent).forEach(p=>p.hidden=p.dataset.panel!==name);}
  function recipeView(recipe,result){const slots=[...(recipe.slots||[])];while(slots.length<9)slots.push(null);const used=[];slots.forEach(s=>{if(s&&!used.some(x=>(x.tag||x.id)===(s.tag||s.id)))used.push(s)});return`<div class="recipe-card"><div class="recipe-title"><strong>${recipeNames[recipe.type]||friendly(recipe.type)}</strong><span>产出 ${recipe.count} 个</span></div><div class="recipe-workbench"><div class="crafting-grid">${slots.slice(0,9).map(s=>s?`<div class="craft-slot">${itemIcon(s.id,'craft-icon')}<small>${escapeHtml(s.name)}</small>${s.tag?'<i>可替换</i>':''}</div>`:'<div class="craft-slot empty-slot"></div>').join('')}</div><span class="craft-arrow">→</span><div class="result-slot">${itemIcon(result.id,'craft-result-icon')}<strong>${escapeHtml(result.name)}</strong><b>×${recipe.count}</b></div></div><div class="ingredient-list"><b>所需材料：</b>${used.length?used.map(s=>`<span>${escapeHtml(s.name)}${s.tag?'（同标签材料均可）':''}</span>`).join(''):'<span>没有普通合成格原料</span>'}</div></div>`;}
  function showItem(id){const i=itemById.get(id)||{id,name:friendly(id),image:'',recipes:[],shops:[],pokemonDrops:[],loot:[],hasSource:false};const recipes=i.recipes.map(r=>recipeView(r,i)).join('');const shops=i.shops.map(s=>`<div class="data-entry"><strong>${escapeHtml(shopNames[s.category]||s.category)}</strong> · 价格 ${escapeHtml(s.price)} 金币</div>`).join('');const drops=i.pokemonDrops.map(d=>`<div class="data-entry"><button class="link-button" data-pokemon="${escapeHtml(d.pokemon)}">${escapeHtml(pokemonById.get(d.pokemon)?.name||friendly(d.pokemon))}</button> · 数量 ${escapeHtml(d.quantity)}${d.chance!=null?` · 概率 ${d.chance}%`:''}</div>`).join('');dialogContent.innerHTML=`<article class="detail"><header class="detail-hero">${itemIcon(i.id,'item-detail-image')}<div><h2>${escapeHtml(i.name)}</h2><p>道具来源与使用方式</p></div></header><details class="tech-details"><summary>查看技术标识</summary><code>${escapeHtml(i.id)}</code></details><section class="detail-section"><h3>合成与加工图示</h3>${recipes||'<p class="empty">未检出以此道具为结果的配方。</p>'}</section><section class="detail-section"><h3>商店来源</h3>${shops||'<p class="empty">默认商店未出售。</p>'}</section><section class="detail-section"><h3>宝可梦掉落</h3>${drops||'<p class="empty">物种数据中未检出此掉落。</p>'}</section><section class="detail-section"><h3>战利品来源</h3>${i.loot.length?`<div class="chip-row">${i.loot.map(x=>`<span class="chip">${escapeHtml(friendly(x))}</span>`).join('')}</div>`:'<p class="empty">未检出战利品表来源。</p>'}</section>${!i.hasSource?'<p class="warning">未检出来源不等于绝对无法获得：它可能来自任务、NPC、结构脚本或模组动态逻辑，建议在游戏内使用 REI 再确认。</p>':''}</article>`;if(!dialog.open)dialog.showModal();}

  $('#pack-lists').innerHTML=[['模组',data.pack.mods],['数据包',data.pack.datapacks],['资源包',data.pack.resourcepacks]].map(([title,list])=>`<details><summary>${title}（${list.length}）</summary><ul class="file-list">${list.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></details>`).join('');
  function showStarters(){const regions={Kanto:'关都',Johto:'城都',Hoenn:'丰缘',Sinnoh:'神奥',Unova:'合众',Kalos:'卡洛斯',Alola:'阿罗拉',Galar:'伽勒尔',Hisui:'洗翠',Paldea:'帕底亚',Pallet:'真新镇特别组',Lumya:'露米娅特别组',Cosplay:'换装特别组'};const describe=raw=>{const parts=raw.split(' '),p=pokemonByEnglish.get(parts[0].toLowerCase());const extras=parts.slice(1).map(x=>{const [k,v]=x.split('=');return `${fieldNames[k]||({level:'等级',gender:'性别',pokeball:'精灵球',moves:'招式',cosplay:'装扮',region_bias:'地区倾向'}[k]||chineseTokens(k))}：${friendly(v)}`}).join('，');return`${p?.name||parts[0]}${extras?'（'+extras+'）':''}`};const panel=$('#starter-panel');panel.hidden=false;panel.innerHTML=`<h3>初始伙伴组（共 ${data.starters.length} 组）</h3><div class="starter-groups">${data.starters.map(g=>`<div class="starter-group"><strong>${escapeHtml(regions[g.name]||g.name)}</strong><p>${g.pokemon.map(x=>escapeHtml(describe(x))).join('<br>')}</p></div>`).join('')}</div>`;panel.scrollIntoView({behavior:'smooth',block:'nearest'});}
  let featured=null;
  function shuffleFeatured(){const pool=data.pokemon.filter(p=>p.image&&p.spawns.length);featured=pool[Math.floor(Math.random()*pool.length)];const card=$('.featured-card');card.classList.add('swap');setTimeout(()=>{if(featured){$('#featured-image').src=featured.image;$('#featured-image').alt=featured.name+'头像';$('#featured-name').textContent=featured.name;$('#featured-meta').textContent=`全国图鉴 #${featured.dex} · ${featured.types.join(' / ')}`;$('#open-featured').dataset.pokemon=featured.id}card.classList.remove('swap')},170);}
  const views=['home','route','pokedex','items','systems'];
  function activateView(id){if(!views.includes(id))id='home';views.forEach(view=>{const section=$('#'+view);section.hidden=view!==id;section.classList.remove('view-enter');if(view===id){void section.offsetWidth;section.classList.add('view-enter')}});$$('.main-nav a,.app-dock a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id));$('#main-nav').classList.remove('open');window.scrollTo({top:0,behavior:location.search||matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}

  document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){selectTab(tab.dataset.tab);return}const form=e.target.closest('[data-form-image]');if(form){$$('.form-card',dialogContent).forEach(x=>x.classList.remove('active'));form.classList.add('active');$('#form-preview-image').src=form.dataset.formImage;$('#form-preview-title').textContent=form.dataset.formLabel;return}const p=e.target.closest('[data-pokemon]');if(p){showPokemon(p.dataset.pokemon);return}const i=e.target.closest('[data-item]');if(i){showItem(i.dataset.item);return}const a=e.target.closest('[data-action]');if(a?.dataset.action==='show-starters'){showStarters();return}if(a?.dataset.action==='shop-items'){$('#source-filter').value='shop';renderItems(true);location.hash='items'}});
  $$('.main-nav a,.app-dock a,.hero-actions a').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href')?.slice(1);if(views.includes(id)){e.preventDefault();if(location.hash==='#'+id)activateView(id);else location.hash=id}}));
  window.addEventListener('hashchange',()=>activateView(location.hash.slice(1)||'home'));
  $('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
  ['pokemon-search','type-filter','gen-filter','spawn-filter'].forEach(id=>$('#'+id).addEventListener('input',()=>renderPokemon(true)));['item-search','namespace-filter','source-filter'].forEach(id=>$('#'+id).addEventListener('input',()=>renderItems(true)));
  $('#pokemon-more').addEventListener('click',()=>{pokemonLimit+=40;renderPokemon()});$('#item-more').addEventListener('click',()=>{itemLimit+=60;renderItems()});
  $('#random-pokemon').addEventListener('click',()=>{const list=filteredPokemon();if(list.length)showPokemon(list[Math.floor(Math.random()*list.length)].id)});$('#shuffle-featured').addEventListener('click',shuffleFeatured);
  $('.menu-button').addEventListener('click',e=>{const open=$('#main-nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)});
  renderPokemon();renderItems();shuffleFeatured();activateView(location.hash.slice(1)||'home');
  const previewParams=new URLSearchParams(location.search);if(previewParams.get('pokemon'))showPokemon(previewParams.get('pokemon'),previewParams.get('tab')||'obtain');else if(previewParams.get('item'))showItem(previewParams.get('item'));
})();
